BEGIN;

CREATE TABLE IF NOT EXISTS todo_list (
    id SERIAL PRIMARY KEY,
    todo_list_name VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todo (
    id SERIAL PRIMARY KEY,
    todo_name VARCHAR(255),
    todo_list_name VARCHAR(255) REFERENCES todo_list (todo_list_name) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL,
    done BOOLEAN NOT NULL
);

COMMIT;